Sys.getenv("R_LIBS_USER")
library("TDA")
args = commandArgs(trailingOnly=TRUE)
X = read.csv(args[1])
#DiagAlphaComplex <- alphaComplexDiag(X=X)
DiagAlphaComplex <- alphaShapeDiag(X=X)
sink(args[2])
print(DiagAlphaComplex[["diagram"]])
